package cn.edu.seu.wh.drools.springboot.demo.mapper;

import cn.edu.seu.wh.drools.springboot.demo.dto.Rule;
import cn.edu.seu.wh.drools.springboot.demo.dto.RuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    long countByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int deleteByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int insert(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int insertSelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    List<Rule> selectByExampleWithBLOBs(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    List<Rule> selectByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    Rule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Rule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Rule record);
}