package rules

import cn.edu.seu.wh.drools.simple.demo.entity.Message;


global java.util.List list

rule "Hello World"
    dialect "mvel"
    salience 3
    when
        m:Message(status==Message.HELLO,msg:message)
    then
        System.out.println(msg);
        list.add(m);
        modify(m){message="Goodbye cruel world!",status=Message.GOODBYE};
end

rule "Good Bye"
    dialect "java"
    when
        Message(status==Message.GOODBYE,msg:message)
    then
        System.out.println(msg);
end